#!/bin/bash

cd $(dirname $0)
. control

function usage {
    cat <<EOF >&2
USAGE
     $(basename $0)
EOF
}
if [ $# -eq 0 ];then
    select_st='
select Mname from Module order by Mname
'
    ${mysql_cmd} "$select_st"
    exit 0
else
    usage
    exit 1
fi
