#!/bin/bash

. /etc/init.d/functions

nice=
force=
RETVAL=
while [ "$1" != "${1##[-+]}" ]; do
	case $1 in
	     -f)
	     	force="--force"
		shift
		;;
	     -n)
	     	nice=$2
		shift 2
		;;
	esac
done
LSB=LSB-1.1 daemon ${force:-} ${nice:-} $*
exit $?
